package ConcateModule;


/**
* ConcateModule/Concate.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcateModule.idl
* Sunday, 28 May, 2023 7:20:19 PM IST
*/

public interface Concate extends ConcateOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Concate
