package ConcateModule;


/**
* ConcateModule/ConcateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcateModule.idl
* Sunday, 28 May, 2023 7:20:19 PM IST
*/

abstract public class ConcateHelper
{
  private static String  _id = "IDL:ConcateModule/Concate:1.0";

  public static void insert (org.omg.CORBA.Any a, ConcateModule.Concate that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ConcateModule.Concate extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ConcateModule.ConcateHelper.id (), "Concate");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ConcateModule.Concate read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ConcateStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ConcateModule.Concate value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ConcateModule.Concate narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ConcateModule.Concate)
      return (ConcateModule.Concate)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ConcateModule._ConcateStub stub = new ConcateModule._ConcateStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ConcateModule.Concate unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ConcateModule.Concate)
      return (ConcateModule.Concate)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ConcateModule._ConcateStub stub = new ConcateModule._ConcateStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
