package ConcateModule;

/**
* ConcateModule/ConcateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcateModule.idl
* Sunday, 28 May, 2023 7:20:19 PM IST
*/

public final class ConcateHolder implements org.omg.CORBA.portable.Streamable
{
  public ConcateModule.Concate value = null;

  public ConcateHolder ()
  {
  }

  public ConcateHolder (ConcateModule.Concate initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConcateModule.ConcateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConcateModule.ConcateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConcateModule.ConcateHelper.type ();
  }

}
