package ConcateModule;


/**
* ConcateModule/ConcateOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcateModule.idl
* Sunday, 28 May, 2023 7:20:19 PM IST
*/

public interface ConcateOperations 
{
  String concatString (String s1, String s2);
} // interface ConcateOperations
